server:
  port: ${APP_PORT:3000}
# ===============================
# Logging config
# ===============================
logging:
  file:
    path: ./logs
  level:
    root: INFO
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{45} - %msg | traceId=%X{traceId:-NA}%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{45} - %msg | traceId=%X{traceId:-NA}%n"

spring:
  datasource:
    url: jdbc:postgresql://${CHAT_SYSTEM_DB_HOST}:${CHAT_SYSTEM_DB_PORT}/${CHAT_SYSTEM_DB_NAME}
    username: ${CHAT_SYSTEM_DB_USERNAME}
    password: ${CHAT_SYSTEM_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: HikariPool-19
  # ===============================
  # Hibernate Configuration
  # ===============================
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:create}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
# ===============================
#  Minio Configuration
# ===============================
minio:
  url: http://${CHAT_SYSTEM_MINIO_HOST}:${CHAT_SYSTEM_MINIO_PORT}
  access-key: ${CHAT_SYSTEM_MINIO_ACCESS_KEY}
  secret-key: ${CHAT_SYSTEM_MINIO_SECRET_KEY}
# ===============================
#  JWT Configuration
# ===============================
jwt:
  secret: ${JWT_SECRET:change-me-in-prod-please-very-strong-secret-key}
  issuer: chat-system
  expiry-minutes: 60
