server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: ./promtail-positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: spring-boot-logs
    static_configs:
      - targets:
          - host.docker.internal
        labels:
          job: chat-system-logs
          __path__: /var/logs/*.log